import './style.css'
import './index.css'
import javascriptLogo from './assets/javascript.svg'
import viteLogo from './assets/vite.svg'
import heroImg from './assets/hero.png'
import { setupCounter } from './counter.js'

import './gamesetup.js'
import './input.js'
import './tiles.js'
import './state.js'
import './audio.js'
import './lockpick.js'
import './player.js'
import './interactives.js'
import './enemy.js'
import './hud.js'
import './particles.js'
import './game.js'
import './shop.js'
